events {}

http {
    server {
        listen 80;

        # 1. Vers le Frontend
        location / {
            proxy_pass http://webapp:80;
        }

        # 2. Vers le Backend
        location /api/ {
            proxy_pass http://spring-api:8080;
        }
    }
}